"""
Ahmad Mohmand
Math Worksheet Generator
This module generates customizable math worksheets for high school students.
"""

from datetime import datetime
from pathlib import Path
import random


def generate_linear_equation():
    """Generate a random linear equation: ax + b = c"""
    a = random.randint(2, 10)
    b = random.randint(-20, 20)
    c = random.randint(-50, 50)

    # Calculate the answer
    x = (c - b) / a

    equation = f"{a}x + ({b}) = {c}" if b >= 0 else f"{a}x - {abs(b)} = {c}"
    return equation, round(x, 2)


def generate_arithmetic_problem():
    """Generate a random arithmetic problem"""
    operations = ['+', '-', '*', '/']
    op = random.choice(operations)

    if op == '/':
        # For division, ensure clean division
        divisor = random.randint(2, 12)
        answer = random.randint(1, 20)
        num1 = divisor * answer
        num2 = divisor
    else:
        num1 = random.randint(10, 100)
        num2 = random.randint(2, 50)

    problem = f"{num1} {op} {num2}"

    if op == '+':
        answer = num1 + num2
    elif op == '-':
        answer = num1 - num2
    elif op == '*':
        answer = num1 * num2
    else:  # division
        answer = num1 // num2

    return problem, answer


def create_worksheet(num_algebra=10, num_arithmetic=10):
    """
    Create a complete math worksheet with problems and answer key.

    Args:
        num_algebra: Number of algebra problems to generate
        num_arithmetic: Number of arithmetic problems to generate

    Returns:
        Tuple of (worksheet_content, answer_key_content)
    """
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    # Build worksheet header
    worksheet = f"""
{'=' * 60}
MATH PRACTICE WORKSHEET
Generated by Ahmad Mohmand's Worksheet Generator
Date: {timestamp}
{'=' * 60}

INSTRUCTIONS: Solve all problems. Show your work!

"""

    # Build answer key
    answer_key = f"""
{'=' * 60}
ANSWER KEY
{'=' * 60}

"""

    # Generate Algebra Problems
    worksheet += "SECTION A: Solve for x\n"
    worksheet += "-" * 40 + "\n\n"
    answer_key += "SECTION A: Algebra Solutions\n"
    answer_key += "-" * 40 + "\n\n"

    for i in range(1, num_algebra + 1):
        equation, answer = generate_linear_equation()
        worksheet += f"{i}. {equation}\n\n   x = __________\n\n"
        answer_key += f"{i}. {equation}\n   x = {answer}\n\n"

    # Generate Arithmetic Problems
    worksheet += "\n" + "=" * 60 + "\n\n"
    worksheet += "SECTION B: Calculate\n"
    worksheet += "-" * 40 + "\n\n"
    answer_key += "\n" + "=" * 60 + "\n\n"
    answer_key += "SECTION B: Arithmetic Solutions\n"
    answer_key += "-" * 40 + "\n\n"

    for i in range(1, num_arithmetic + 1):
        problem, answer = generate_arithmetic_problem()
        worksheet += f"{i}. {problem} = __________\n\n"
        answer_key += f"{i}. {problem} = {answer}\n\n"

    worksheet += "=" * 60 + "\n"
    answer_key += "=" * 60 + "\n"

    return worksheet, answer_key


def save_worksheet(worksheet_content, answer_key_content):
    """Save worksheet and answer key to the artifacts folder."""
    # Create artifacts directory if it doesn't exist
    artifacts_dir = Path("artifacts")
    artifacts_dir.mkdir(exist_ok=True)

    # Generate filenames with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    worksheet_file = artifacts_dir / f"worksheet_{timestamp}.txt"
    answer_file = artifacts_dir / f"answer_key_{timestamp}.txt"

    # Save files
    worksheet_file.write_text(worksheet_content)
    answer_file.write_text(answer_key_content)

    return worksheet_file, answer_file


def main():
    """Generate and save a math worksheet."""
    print("=" * 60)
    print("Math Worksheet Generator - Ahmad Mohmand")
    print("=" * 60)
    print("\nGenerating worksheet...")

    # Create worksheet with 8 algebra problems and 12 arithmetic problems
    worksheet, answer_key = create_worksheet(num_algebra=8, num_arithmetic=12)

    # Save to files
    worksheet_file, answer_file = save_worksheet(worksheet, answer_key)

    print(f"\n✓ Worksheet saved to: {worksheet_file}")
    print(f"✓ Answer key saved to: {answer_file}")
    print("\nWorksheet Preview:")
    print("-" * 60)
    print(worksheet[:500] + "...\n")
    print("=" * 60)
    print("Worksheet generation complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
